import { Translation, Language, Persona, InspirationVideo } from './types';

export const INSPIRATION_VIDEOS: InspirationVideo[] = [
  { id: '1', title: 'O Shampoo vs A Lama (Pet Shop)', thumbnail: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=400&h=600&fit=crop', url: 'https://www.tiktok.com/search?q=objetos+falantes+nicho+pet', niche: 'Pet Shop' },
  { id: '2', title: 'A Balança Sincera (Nutrição)', thumbnail: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=600&fit=crop', url: 'https://www.tiktok.com/search?q=talking+objects+nutrition', niche: 'Saúde' },
  { id: '3', title: 'O Código de Processo Civil (Direito)', thumbnail: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400&h=600&fit=crop', url: 'https://www.tiktok.com/search?q=lawyer+memes+talking+objects', niche: 'Advocacia' }
];

const COMMON_NICHES_PT = [
  'Cozinha & Alimentos', 'Pet Shop', 'Saúde & Higiene', 'Finanças',
  'Fé Cristã', 'Saúde Fitness', 'Nutricionista', 'Cabeleireira', 'Estética',
  'Manicure', 'Advogados', 'Psicóloga', 'Cirurgião Plástico', 'Confeiteira',
  'Papelaria Personalizada', 'Tarô', 'Dona de Casa', 'Educação',
  'Relacionamento', 'Tecnologia', 'Imobiliária', 'Personal Trainer'
];

const COMMON_NICHES_EN = [
  'Kitchen & Food', 'Pet Shop', 'Health & Hygiene', 'Finance',
  'Christian Faith', 'Health & Fitness', 'Nutritionist', 'Hairdresser', 'Esthetics',
  'Manicure', 'Lawyers', 'Psychologist', 'Plastic Surgeon', 'Baker',
  'Custom Stationery', 'Tarot', 'Housewife', 'Education',
  'Relationships', 'Technology', 'Real Estate', 'Personal Trainer'
];

const COMMON_NICHES_ES = [
  'Cocina y Alimentos', 'Tienda de Mascotas', 'Salud e Higiene', 'Finanzas',
  'Fe Cristiana', 'Salud y Fitness', 'Nutricionista', 'Peluquera', 'Estética',
  'Manicura', 'Abogados', 'Psicóloga', 'Cirujano Plástico', 'Repostera',
  'Papelería Personalizada', 'Tarot', 'Ama de Casa', 'Educación',
  'Relaciones', 'Tecnología', 'Inmobiliaria', 'Personal Trainer'
];

const PERSONAS_PT: Persona[] = [
  { id: 'sarcastic', name: 'O Café Sarcástico', emoji: '☕', description: 'Debochado e sincero sobre produtividade.', trait: 'Sarcástico, direto, usa gírias de cansaço corporativo.' },
  { id: 'angry_bill', name: 'O Boleto Bravo', emoji: '💸', description: 'Reclama que ninguém quer pagá-lo.', trait: 'Irritado, ansioso, voz apressada.' },
  { id: 'wise_vitamin', name: 'A Vitamina Sábia', emoji: '💊', description: 'Dá conselhos profundos sobre saúde.', trait: 'Sereno, voz profunda, autoritário mas gentil.' },
  { id: 'gossip_makeup', name: 'A Make Fofoqueira', emoji: '💄', description: 'Conta segredos do nicho de beleza.', trait: 'Entusiasmado, fala rápido, usa "Miga" e "Babado".' }
];

const PERSONAS_EN: Persona[] = [
  { id: 'sarcastic', name: 'Sarcastic Coffee', emoji: '☕', description: 'Mocking and sincere about productivity.', trait: 'Sarcastic, direct, uses corporate burnout slang.' },
  { id: 'angry_bill', name: 'Angry Bill', emoji: '💸', description: 'Complains that no one wants to pay him.', trait: 'Irritated, anxious, fast-paced voice.' },
  { id: 'wise_vitamin', name: 'Wise Vitamin', emoji: '💊', description: 'Gives deep advice about health.', trait: 'Serene, deep voice, authoritative but kind.' },
  { id: 'gossip_makeup', name: 'Gossip Makeup', emoji: '💄', description: 'Tells secrets of the beauty niche.', trait: 'Enthusiastic, fast speaker, uses "Girlie" and "Tea".' }
];

const PERSONAS_ES: Persona[] = [
  { id: 'sarcastic', name: 'El Café Sarcástico', emoji: '☕', description: 'Sarcástico y sincero sobre la productividad.', trait: 'Sarcástico, directo, usa jerga de agotamiento corporativo.' },
  { id: 'angry_bill', name: 'La Factura Enojada', emoji: '💸', description: 'Se queja de que nadie quiere pagarla.', trait: 'Irritado, ansioso, voz apresurada.' },
  { id: 'wise_vitamin', name: 'La Vitamina Sabia', emoji: '💊', description: 'Da consejos profundos sobre salud.', trait: 'Sereno, voz profunda, autoritario pero gentil.' },
  { id: 'gossip_makeup', name: 'El Maquillaje Chismoso', emoji: '💄', description: 'Cuenta secretos del nicho de belleza.', trait: 'Entusiasta, habla rápido, usa "Amiga" y "Chisme".' }
];

export const TRANSLATIONS: Record<Language, Translation> = {
  PT: {
    title: 'ViraExpress',
    back: 'Voltar',
    copy: 'Copiar',
    copied: 'Copiado!',
    save: 'Salvar',
    delete: 'Excluir',
    loading: 'Carregando...',
    error: 'Ocorreu um erro',
    success: 'Sucesso!',
    logout: 'Sair',
    loginSubtitle: 'Crie vídeos virais com objetos falantes',
    emailLabel: 'Seu e-mail',
    passwordLabel: 'Sua senha',
    loginButton: 'ENTRAR',
    personaBank: 'Banco de Personas (Tom de Voz)',
    generateIdeasTitle: 'Gerador de Ideias',
    chooseNiche: 'Escolher Nicho',
    manualNiche: 'Manual',
    nicheLabel: 'Nicho de atuação',
    formatLabel: 'Formato do vídeo',
    generateButton: 'GERAR 10 IDEIAS AGORA',
    generateMore: 'GERAR MAIS 10 IDEIAS',
    generatePrompts: 'GERAR ESTRATÉGIA',
    historyTitle: 'Histórico de Criação',
    noHistory: 'Nenhum vídeo salvo ainda.',
    muralTitle: 'Mural de Tendências Virais',
    muralSubtitle: 'A Biblioteca de Ouro de Objetos Falantes',
    searchMural: 'Buscar nicho no mural...',
    discover: 'Descobrir',
    viewTikTok: 'Ver no TikTok',
    niches: COMMON_NICHES_PT,
    personas: PERSONAS_PT,
    strategyReady: 'ESTRUTURA VIRAL ✅',
    readySubtitle: 'Pronto para execução imediata',
    viralScoreTitle: 'Termômetro de Viralização',
    hookLabel: 'Gancho',
    retentionLabel: 'Retenção',
    ctaLabel: 'CTA',
    feedbackLabel: 'Feedback Técnico',
    watermarkTitle: 'Personalizar Marca de Proteção',
    watermarkPlaceholder: '@SeuHandle',
    applyHandle: 'Aplicar no @Handle',
    imagePromptTitle: '1️⃣ PROMPT IMAGEN (PIXAR STYLE)',
    scriptTitle: '2️⃣ ROTEIRO (GÍRIAS 2025/26)',
    videoPromptTitle: '3️⃣ MASTER PROMPT VEO 3 (VÍDEO)',
    copyVideoPrompt: 'COPIAR PROMPT DE VÍDEO',
    refineTitle: 'Refinar Estratégia',
    refinePlaceholder: 'Ex: Deixe o roteiro mais curto...',
    adjust: 'Ajustar',
    flowTitle: 'Fluxo de Montagem Sugerido',
    myVideoTitle: 'MEU VÍDEO PRONTO',
    myVideoSubtitle: 'Centralize aqui seu vídeo finalizado',
    uploadVideo: 'SUBIR VÍDEO FINAL',
    noVideo: 'Nenhum vídeo salvo ainda.',
    dashboardButton: 'Dashboard',
    saveToHistoryButton: '💾 SALVAR ESTRATÉGIA NO HISTÓRICO',
    step: 'PASSO',
    stepImage: 'IMAGEM',
    stepVideo: 'VÍDEO',
    stepAudio: 'ÁUDIO',
    stepRemove: 'LOGO OFF',
    stepImageDesc: 'Gere no Gemini usando os prompts acima.',
    stepVideoDesc: 'Anime no VEO 3 com o Master Prompt.',
    stepAudioDesc: 'Grave o roteiro no CapCut com a voz do personagem.',
    stepRemoveDesc: 'Se houver marca d\'água da IA, remova com o link abaixo.',
    viralScore: 'Viral Score',
    viralDescription: 'Análise de potencial de viralização',
    hookScore: 'Gancho',
    retentionScore: 'Retenção',
    ctaScore: 'Chamada',
    trendScore: 'Tendência'
  },
  EN: {
    title: 'ViraExpress',
    back: 'Back',
    copy: 'Copy',
    copied: 'Copied!',
    save: 'Save',
    delete: 'Delete',
    loading: 'Loading...',
    error: 'An error occurred',
    success: 'Success!',
    logout: 'Logout',
    loginSubtitle: 'Create viral videos with talking objects',
    emailLabel: 'Your email',
    passwordLabel: 'Your password',
    loginButton: 'LOGIN',
    personaBank: 'Persona Bank (Tone of Voice)',
    generateIdeasTitle: 'Idea Generator',
    chooseNiche: 'Choose Niche',
    manualNiche: 'Manual',
    nicheLabel: 'Niche of activity',
    formatLabel: 'Video format',
    generateButton: 'GENERATE 10 IDEAS NOW',
    generateMore: 'GENERATE 10 MORE IDEAS',
    generatePrompts: 'GENERATE STRATEGY',
    historyTitle: 'Creation History',
    noHistory: 'No videos saved yet.',
    muralTitle: 'Viral Trends Mural',
    muralSubtitle: 'The Golden Library of Talking Objects',
    searchMural: 'Search niche in mural...',
    discover: 'Discover',
    viewTikTok: 'View on TikTok',
    niches: COMMON_NICHES_EN,
    personas: PERSONAS_EN,
    strategyReady: 'VIRAL STRUCTURE ✅',
    readySubtitle: 'Ready for immediate execution',
    viralScoreTitle: 'Viral Potentiometer',
    hookLabel: 'Hook',
    retentionLabel: 'Retention',
    ctaLabel: 'CTA',
    feedbackLabel: 'Technical Feedback',
    watermarkTitle: 'Customize Protection Mark',
    watermarkPlaceholder: '@YourHandle',
    applyHandle: 'Apply to @Handle',
    imagePromptTitle: '1️⃣ IMAGE PROMPT (PIXAR STYLE)',
    scriptTitle: '2️⃣ SCRIPT (2025/26 SLANGS)',
    videoPromptTitle: '3️⃣ MASTER PROMPT VEO 3 (VIDEO)',
    copyVideoPrompt: 'COPY VIDEO PROMPT',
    refineTitle: 'Refine Strategy',
    refinePlaceholder: 'Ex: Make the script shorter...',
    adjust: 'Adjust',
    flowTitle: 'Suggested Assembly Flow',
    myVideoTitle: 'MY READY VIDEO',
    myVideoSubtitle: 'Centralize your finished video here',
    uploadVideo: 'UPLOAD FINAL VIDEO',
    noVideo: 'No video saved yet.',
    dashboardButton: 'Dashboard',
    saveToHistoryButton: '💾 SAVE STRATEGY TO HISTORY',
    step: 'STEP',
    stepImage: 'IMAGE',
    stepVideo: 'VIDEO',
    stepAudio: 'AUDIO',
    stepRemove: 'LOGO OFF',
    stepImageDesc: 'Generate in Gemini using the prompts above.',
    stepVideoDesc: 'Animate in VEO 3 with the Master Prompt.',
    stepAudioDesc: 'Record script in CapCut with persona voice.',
    stepRemoveDesc: 'If there is an AI watermark, remove it with the link below.',
    viralScore: 'Viral Score',
    viralDescription: 'Viral potential analysis',
    hookScore: 'Hook',
    retentionScore: 'Retention',
    ctaScore: 'CTA',
    trendScore: 'Trend'
  },
  ES: {
    title: 'ViraExpress',
    back: 'Volver',
    copy: 'Copiar',
    copied: '¡Copiado!',
    save: 'Guardar',
    delete: 'Eliminar',
    loading: 'Cargando...',
    error: 'Ocurrió un error',
    success: '¡Éxito!',
    logout: 'Salir',
    loginSubtitle: 'Crea videos virales con objetos parlantes',
    emailLabel: 'Tu e-mail',
    passwordLabel: 'Tu contraseña',
    loginButton: 'ENTRAR',
    personaBank: 'Banco de Personas (Tono de Voz)',
    generateIdeasTitle: 'Generador de Ideas',
    chooseNiche: 'Elegir Nicho',
    manualNiche: 'Manual',
    nicheLabel: 'Nicho de actuación',
    formatLabel: 'Formato de video',
    generateButton: 'GENERAR 10 IDEAS AHORA',
    generateMore: 'GENERAR 10 IDEAS MÁS',
    generatePrompts: 'GENERAR ESTRATEGIA',
    historyTitle: 'Historial de Creación',
    noHistory: 'Ningún video guardado aún.',
    muralTitle: 'Mural de Tendencias Virales',
    muralSubtitle: 'La Biblioteca de Oro de Objetos Parlantes',
    searchMural: 'Buscar nicho en mural...',
    discover: 'Descubrir',
    viewTikTok: 'Ver en TikTok',
    niches: COMMON_NICHES_ES,
    personas: PERSONAS_ES,
    strategyReady: 'ESTRUCTURA VIRAL ✅',
    readySubtitle: 'Listo para ejecución imediata',
    viralScoreTitle: 'Termómetro de Viralização',
    hookLabel: 'Gancho',
    retentionLabel: 'Retención',
    ctaLabel: 'CTA',
    feedbackLabel: 'Feedback Técnico',
    watermarkTitle: 'Personalizar Marca de Proteção',
    watermarkPlaceholder: '@TuHandle',
    applyHandle: 'Aplicar en @Handle',
    imagePromptTitle: '1️⃣ PROMPT IMAGEN (PIXAR STYLE)',
    scriptTitle: '2️⃣ GUIÓN (JERGA 2025/26)',
    videoPromptTitle: '3️⃣ MASTER PROMPT VEO 3 (VIDEO)',
    copyVideoPrompt: 'COPIAR PROMPT DE VIDEO',
    refineTitle: 'Refinar Estratégia',
    refinePlaceholder: 'Ej: Haz el guión mais curto...',
    adjust: 'Ajustar',
    flowTitle: 'Flujo de Montaje Sugerido',
    myVideoTitle: 'MI VIDEO LISTO',
    myVideoSubtitle: 'Centraliza tu video finalizado aquí',
    uploadVideo: 'SUBIR VIDEO FINAL',
    noVideo: 'Ningún video guardado aún.',
    dashboardButton: 'Dashboard',
    saveToHistoryButton: '💾 GUARDAR ESTRATEGIA EM HISTORIAL',
    step: 'PASO',
    stepImage: 'IMAGEN',
    stepVideo: 'VIDEO',
    stepAudio: 'AUDIO',
    stepRemove: 'LOGO OFF',
    stepImageDesc: 'Genera en Gemini usando los prompts de arriba.',
    stepVideoDesc: 'Anima en VEO 3 con el Master Prompt.',
    stepAudioDesc: 'Graba el guión en CapCut con la voz del personagem.',
    stepRemoveDesc: 'Si hay marca de agua de IA, quítala con el link de abajo.',
    viralScore: 'Viral Score',
    viralDescription: 'Análisis de potencial viral',
    hookScore: 'Gancho',
    retentionScore: 'Retención',
    ctaScore: 'Llamada',
    trendScore: 'Tendencia'
  }
};
